
export const countries = [
  { name: "Afghanistan", value: "Afghanistan" },
  { name: "Afrique du Sud", value: "Afrique du Sud" },
  { name: "Albanie", value: "Albanie" },
  { name: "Algérie", value: "Algérie" },
  { name: "Allemagne", value: "Allemagne" },
  { name: "Andorre", value: "Andorre" },
  { name: "Angola", value: "Angola" },
  { name: "Antigua-et-Barbuda", value: "Antigua-et-Barbuda" },
  { name: "Arabie Saoudite", value: "Arabie Saoudite" },
  { name: "Argentine", value: "Argentine" },
  { name: "Arménie", value: "Arménie" },
  { name: "Australie", value: "Australie" },
  { name: "Autriche", value: "Autriche" },
  { name: "Azerbaïdjan", value: "Azerbaïdjan" },
  { name: "Bahamas", value: "Bahamas" },
  { name: "Bahreïn", value: "Bahreïn" },
  { name: "Bangladesh", value: "Bangladesh" },
  { name: "Barbade", value: "Barbade" },
  { name: "Belgique", value: "Belgique" },
  { name: "Belize", value: "Belize" },
  { name: "Bénin", value: "Bénin" },
  { name: "Bhoutan", value: "Bhoutan" },
  { name: "Biélorussie", value: "Biélorussie" },
  { name: "Birmanie", value: "Birmanie" },
  { name: "Bolivie", value: "Bolivie" },
  { name: "Bosnie-Herzégovine", value: "Bosnie-Herzégovine" },
  { name: "Botswana", value: "Botswana" },
  { name: "Brésil", value: "Brésil" },
  { name: "Brunei", value: "Brunei" },
  { name: "Bulgarie", value: "Bulgarie" },
  { name: "Burkina Faso", value: "Burkina Faso" },
  { name: "Burundi", value: "Burundi" },
  { name: "Cambodge", value: "Cambodge" },
  { name: "Cameroun", value: "Cameroun" },
  { name: "Canada", value: "Canada" },
  { name: "Cap-Vert", value: "Cap-Vert" },
  { name: "Chili", value: "Chili" },
  { name: "Chine", value: "Chine" },
  { name: "Chypre", value: "Chypre" },
  { name: "Colombie", value: "Colombie" },
  { name: "Comores", value: "Comores" },
  { name: "Corée du Nord", value: "Corée du Nord" },
  { name: "Corée du Sud", value: "Corée du Sud" },
  { name: "Costa Rica", value: "Costa Rica" },
  { name: "Côte d'Ivoire", value: "Côte d'Ivoire" },
  { name: "Croatie", value: "Croatie" },
  { name: "Cuba", value: "Cuba" },
  { name: "Danemark", value: "Danemark" },
  { name: "Djibouti", value: "Djibouti" },
  { name: "Dominique", value: "Dominique" },
  { name: "Égypte", value: "Égypte" },
  { name: "Émirats arabes unis", value: "Émirats arabes unis" },
  { name: "Équateur", value: "Équateur" },
  { name: "Érythrée", value: "Érythrée" },
  { name: "Espagne", value: "Espagne" },
  { name: "Estonie", value: "Estonie" },
  { name: "Eswatini", value: "Eswatini" },
  { name: "États-Unis", value: "États-Unis" },
  { name: "Éthiopie", value: "Éthiopie" },
  { name: "Fidji", value: "Fidji" },
  { name: "Finlande", value: "Finlande" },
  { name: "France", value: "France" },
  { name: "Gabon", value: "Gabon" },
  { name: "Gambie", value: "Gambie" },
  { name: "Géorgie", value: "Géorgie" },
  { name: "Ghana", value: "Ghana" },
  { name: "Grèce", value: "Grèce" },
  { name: "Grenade", value: "Grenade" },
  { name: "Guatemala", value: "Guatemala" },
  { name: "Guinée", value: "Guinée" },
  { name: "Guinée équatoriale", value: "Guinée équatoriale" },
  { name: "Guinée-Bissau", value: "Guinée-Bissau" },
  { name: "Guyana", value: "Guyana" },
  { name: "Honduras", value: "Honduras" },
  { name: "Hongrie", value: "Hongrie" },
  { name: "Îles Cook", value: "Îles Cook" },
  { name: "Îles Marshall", value: "Îles Marshall" },
  { name: "Îles Salomon", value: "Îles Salomon" },
  { name: "Inde", value: "Inde" },
  { name: "Indonésie", value: "Indonésie" },
  { name: "Irak", value: "Irak" },
  { name: "Iran", value: "Iran" },
  { name: "Irlande", value: "Irlande" },
  { name: "Islande", value: "Islande" },
  { name: "Israël", value: "Israël" },
  { name: "Italie", value: "Italie" },
  { name: "Jamaïque", value: "Jamaïque" },
  { name: "Japon", value: "Japon" },
  { name: "Jordanie", value: "Jordanie" },
  { name: "Kazakhstan", value: "Kazakhstan" },
  { name: "Kenya", value: "Kenya" },
  { name: "Kirghizistan", value: "Kirghizistan" },
  { name: "Kiribati", value: "Kiribati" },
  { name: "Koweït", value: "Koweït" },
  { name: "Laos", value: "Laos" },
  { name: "Lesotho", value: "Lesotho" },
  { name: "Lettonie", value: "Lettonie" },
  { name: "Liban", value: "Liban" },
  { name: "Libéria", value: "Libéria" },
  { name: "Libye", value: "Libye" },
  { name: "Liechtenstein", value: "Liechtenstein" },
  { name: "Lituanie", value: "Lituanie" },
  { name: "Luxembourg", value: "Luxembourg" },
  { name: "Macédoine du Nord", value: "Macédoine du Nord" },
  { name: "Madagascar", value: "Madagascar" },
  { name: "Malaisie", value: "Malaisie" },
  { name: "Malawi", value: "Malawi" },
  { name: "Maldives", value: "Maldives" },
  { name: "Mali", value: "Mali" },
  { name: "Malte", value: "Malte" },
  { name: "Maroc", value: "Maroc" },
  { name: "Maurice", value: "Maurice" },
  { name: "Mauritanie", value: "Mauritanie" },
  { name: "Mexique", value: "Mexique" },
  { name: "Micronésie", value: "Micronésie" },
  { name: "Moldavie", value: "Moldavie" },
  { name: "Monaco", value: "Monaco" },
  { name: "Mongolie", value: "Mongolie" },
  { name: "Monténégro", value: "Monténégro" },
  { name: "Mozambique", value: "Mozambique" },
  { name: "Namibie", value: "Namibie" },
  { name: "Nauru", value: "Nauru" },
  { name: "Népal", value: "Népal" },
  { name: "Nicaragua", value: "Nicaragua" },
  { name: "Niger", value: "Niger" },
  { name: "Nigéria", value: "Nigéria" },
  { name: "Niue", value: "Niue" },
  { name: "Norvège", value: "Norvège" },
  { name: "Nouvelle-Zélande", value: "Nouvelle-Zélande" },
  { name: "Oman", value: "Oman" },
  { name: "Ouganda", value: "Ouganda" },
  { name: "Ouzbékistan", value: "Ouzbékistan" },
  { name: "Pakistan", value: "Pakistan" },
  { name: "Palaos", value: "Palaos" },
  { name: "Panama", value: "Panama" },
  { name: "Papouasie-Nouvelle-Guinée", value: "Papouasie-Nouvelle-Guinée" },
  { name: "Paraguay", value: "Paraguay" },
  { name: "Pays-Bas", value: "Pays-Bas" },
  { name: "Pérou", value: "Pérou" },
  { name: "Philippines", value: "Philippines" },
  { name: "Pologne", value: "Pologne" },
  { name: "Portugal", value: "Portugal" },
  { name: "Qatar", value: "Qatar" },
  { name: "République centrafricaine", value: "République centrafricaine" },
  { name: "République démocratique du Congo", value: "République démocratique du Congo" },
  { name: "République Dominicaine", value: "République Dominicaine" },
  { name: "République du Congo", value: "République du Congo" },
  { name: "République tchèque", value: "République tchèque" },
  { name: "Roumanie", value: "Roumanie" },
  { name: "Royaume-Uni", value: "Royaume-Uni" },
  { name: "Russie", value: "Russie" },
  { name: "Rwanda", value: "Rwanda" },
  { name: "Saint-Christophe-et-Niévès", value: "Saint-Christophe-et-Niévès" },
  { name: "Saint-Marin", value: "Saint-Marin" },
  { name: "Saint-Vincent-et-les-Grenadines", value: "Saint-Vincent-et-les-Grenadines" },
  { name: "Sainte-Lucie", value: "Sainte-Lucie" },
  { name: "Salvador", value: "Salvador" },
  { name: "Samoa", value: "Samoa" },
  { name: "Sao Tomé-et-Principe", value: "Sao Tomé-et-Principe" },
  { name: "Sénégal", value: "Sénégal" },
  { name: "Serbie", value: "Serbie" },
  { name: "Seychelles", value: "Seychelles" },
  { name: "Sierra Leone", value: "Sierra Leone" },
  { name: "Singapour", value: "Singapour" },
  { name: "Slovaquie", value: "Slovaquie" },
  { name: "Slovénie", value: "Slovénie" },
  { name: "Somalie", value: "Somalie" },
  { name: "Soudan", value: "Soudan" },
  { name: "Soudan du Sud", value: "Soudan du Sud" },
  { name: "Sri Lanka", value: "Sri Lanka" },
  { name: "Suède", value: "Suède" },
  { name: "Suisse", value: "Suisse" },
  { name: "Suriname", value: "Suriname" },
  { name: "Syrie", value: "Syrie" },
  { name: "Tadjikistan", value: "Tadjikistan" },
  { name: "Tanzanie", value: "Tanzanie" },
  { name: "Tchad", value: "Tchad" },
  { name: "Thaïlande", value: "Thaïlande" },
  { name: "Timor oriental", value: "Timor oriental" },
  { name: "Togo", value: "Togo" },
  { name: "Tonga", value: "Tonga" },
  { name: "Trinité-et-Tobago", value: "Trinité-et-Tobago" },
  { name: "Tunisie", value: "Tunisie" },
  { name: "Turkménistan", value: "Turkménistan" },
  { name: "Turquie", value: "Turquie" },
  { name: "Tuvalu", value: "Tuvalu" },
  { name: "Ukraine", value: "Ukraine" },
  { name: "Uruguay", value: "Uruguay" },
  { name: "Vanuatu", value: "Vanuatu" },
  { name: "Vatican", value: "Vatican" },
  { name: "Venezuela", value: "Venezuela" },
  { name: "Viêt Nam", value: "Viêt Nam" },
  { name: "Yémen", value: "Yémen" },
  { name: "Zambie", value: "Zambie" },
  { name: "Zimbabwe", value: "Zimbabwe" }
];
